version: 1.0.{build}
image: Ubuntu2004

init:
  - echo "Using Ubuntu Linux image with Java 17"

install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-17-jdk maven

build_script:
  - java -version
  - mvn -version
  - mvn clean install

cache:
  - ~/.m2  # Cache Maven dependencies

artifacts:
  - path: target/*.jar
